Note in the GCP Guide about GPU All Regions quota
I got this:
    ERROR: (gcloud.compute.instances.create) Could not fetch resource:
     - Quota 'GPUS_ALL_REGIONS' exceeded. Limit: 0.0 globally.
and it seems that the default quota is 0. So everyone would need to do this.