Add a section regarding the start notebook
The current docs are lacking. 
The following breaks. 
1. Create notebook and start for the first time, all is well.
2. Stop Notebook.
3. Start Notebook.
4. Try to run notebook with any kernel attached. 
Fail :
" from fastai import *"
ModuleNotFoundError: No module named 'fastai'

This solves the issue.